### PR TITLE
Update for latest nightly

### PR DESCRIPTION
**Pull request by jyn514**
NOT A CONTRIBUTION just fucking around

At some point you may want to pin a specific version of nightly, but I'll leave that for you to decide

### CODE REVIEW

**Comment by largenumberhere** [comment]
This one actually worked for me to build today :D. The main repository refused to compile for me even after setting it to nightly 2023-02-08 and installing all the components

**Comment by thomcc** [comment]
Lol thanks.

**Comment by thomcc** [comment]
> At some point you may want to pin a specific version of nightly

Having to fuck around a bit to get it to work is the cost of using ubrustc.

**Comment by thomcc** [comment]
> This one actually worked for me to build today :D. The main repository refused to compile for me even after setting it to nightly 2023-02-08 and installing all the components

Wait please don't tell me you're actually using this for anything.

**Comment by largenumberhere** [comment]
> > This one actually worked for me to build today :D. The main repository refused to compile for me even after setting it to nightly 2023-02-08 and installing all the components
> 
> Wait please don't tell me you're actually using this for anything.

God no xP. Just having a bit of fun with it

**Pull request merged**
